### ISSUE TITLE
npm install安装失败

### ISSUE THREAD

**Issue by lyz05** [next-theme/hexo-next-valine#5]
可能是因为默认分支改为main分支后导致安装失败
![image](https://user-images.githubusercontent.com/11796777/128195480-99c841fc-e7e7-4de3-a47a-4fb8f0aa1541.png)

**Comment by stevenjoezhang** [comment]
我试了一下，用npm安装没有问题。你用的似乎是cnpm，和npm不一样的。

**Comment by lyz05** [comment]
是的 用npm安装就没有问题了
